JSdocs for autocomplete, lookup, and search components
blackbaud/skyux-lookup pull request #129
Opened 2020-09-14 22:24 UTC by Blackbaud-DeniseCisneros

2020-09-14 22:43 UTC, blackbaud-ado commented
Preview build at [https://host.nxt.blackbaud.com/skyux-lookup?_sp.spa=pr-search-lookup-autocomplete-jsdocs](https://host.nxt.blackbaud.com/skyux-lookup?_sp.spa=pr-search-lookup-autocomplete-jsdocs)

2020-09-16 17:25 UTC, Blackbaud-AlexKingman reviewed
Left some comments for the autocomplete component. Also we'll need to...
1. Add `@internal` to the following: `SkyAutocompleteAdapterService`, `SkyAutocompleteDefaultSearchFunctionOptions`, `SkyAutocompleteInputTextChange`, and `SkyAutocompleteSearchResult`.
2. In the `SkyAutocompleteInputDirective`, change the @default value for disabled to `false` (need to remove the quotes b/c its a boolean not a string).

2020-09-16 17:25 UTC, Blackbaud-AlexKingman commented on src/app/public/modules/autocomplete/autocomplete.component.ts
>    public get selectionChange(): EventEmitter<SkyAutocompleteSelectionChange> {
This event is showing as "Optional." That doesn't really make sense for an event, and is probably a docs-tools bug. I filed an issue here: https://github.com/blackbaud/skyux-docs-tools/issues/132

2020-09-16 17:30 UTC, Blackbaud-AlexKingman commented on src/app/public/modules/autocomplete/autocomplete.component.ts
>    public set search(value: SkyAutocompleteSearchFunction) {
Yep, its a bug. Filed: https://github.com/blackbaud/skyux-docs-tools/issues/133
This shouldn't hold up your PR though.

2020-09-16 17:55 UTC, Blackbaud-AlexKingman reviewed
Lookup component looks great, just need to slap `@internal` on the `SkyLookupAutocompleteAdapter`.

2020-09-16 17:55 UTC, Blackbaud-AlexKingman commented on src/app/public/modules/lookup/lookup-autocomplete-adapter.ts
>    public search: SkyAutocompleteSearchFunction;
The output type `SkyAutocompleteSearchFunction` isn't showing on this docs page, but I'm pretty sure its related to this issue here: https://github.com/blackbaud/skyux-docs-tools/issues/125. Doesn't need to block your PR, just noting it.

2020-09-16 17:55 UTC, Blackbaud-AlexKingman commented on src/app/public/modules/lookup/lookup-autocomplete-adapter.ts
>    public searchFilters: SkyAutocompleteSearchFunctionFilter[];
This output type `SkyAutocompleteSearchFunctionFilter` is also blocked by the same issue above.

2020-09-16 17:58 UTC, Blackbaud-AlexKingman reviewed
Search component looks great. One minor comment and also we'll need to add `@internal` to the `SkySearchAdapterService`.

2020-09-16 17:58 UTC, Blackbaud-AlexKingman commented on src/app/public/modules/search/search.component.ts
> + * devices, and fit to extend the search input to `fit` the width of its container.
Looks like we need to put the tick marks around the prior `fit` (instead of the latter).

2020-09-16 20:12 UTC, blackbaud-ado commented
Preview build at [https://host.nxt.blackbaud.com/skyux-lookup?_sp.spa=pr-search-lookup-autocomplete-jsdocs](https://host.nxt.blackbaud.com/skyux-lookup?_sp.spa=pr-search-lookup-autocomplete-jsdocs)

2020-09-17 18:31 UTC, Blackbaud-AlexKingman requested changes
`SkySearchAdapterService` and `SkyLookupAutocompleteAdapter` will also need to be marked with `@internal`. Then, this is good to go!

2020-09-17 18:34 UTC, blackbaud-ado commented
Preview build at [https://host.nxt.blackbaud.com/skyux-lookup?_sp.spa=pr-search-lookup-autocomplete-jsdocs](https://host.nxt.blackbaud.com/skyux-lookup?_sp.spa=pr-search-lookup-autocomplete-jsdocs)

2020-09-17 18:43 UTC, Blackbaud-AlexKingman approved these changes

2020-09-17 18:54 UTC, blackbaud-ado commented
Preview build at [https://host.nxt.blackbaud.com/skyux-lookup?_sp.spa=pr-search-lookup-autocomplete-jsdocs](https://host.nxt.blackbaud.com/skyux-lookup?_sp.spa=pr-search-lookup-autocomplete-jsdocs)

2020-09-17 19:16 UTC, merged